# Exercícios - DataFrames
## Exercício 1

1. Importe a biblioteca Pandas
2. Crie um dataframe a partir do seguinte dicionário:

```py
carros = {
    'modelo': ['Maruti 800 AC','Maruti Wagon R LXI Minor','Hyundai Verna 1.6 SX', 'Datsun RediGO T Option', 'Honda Amaze VX i-DTEC', 'Maruti Alto LX BSIII', 'Hyundai Xcent 1.2 Kappa S', 'Tata Indigo Grand Petrol', 'Hyundai Creta 1.6 VTVT S', 'Maruti Celerio Green VXI', 'Chevrolet Sail 1.2 Base', 'Tata Indigo Grand Petrol', 'Toyota Corolla Altis 1.8 VL CVT'],
    'ano': [2007, 2007, 2012, 2017, 2014, 2007, 2016, 2014, 2015, 2017, 2015, 2014, 2018],
    'preço': [60000, 135000, 600000, 250000, 450000, 140000, 550000, 240000, 850000, 365000, 260000, 250000, 1650000],
    'combustivel': ['Petrol', 'Petrol', 'Diesel', 'Petrol', 'Diesel', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'CNG', 'Petrol', 'Petrol', 'Petrol']
}
```
3. Mostre na tela o DataFrame criado

In [2]:
import pandas as pd

carros = {
    'modelo': ['Maruti 800 AC','Maruti Wagon R LXI Minor','Hyundai Verna 1.6 SX', 'Datsun RediGO T Option', 'Honda Amaze VX i-DTEC', 'Maruti Alto LX BSIII', 'Hyundai Xcent 1.2 Kappa S', 'Tata Indigo Grand Petrol', 'Hyundai Creta 1.6 VTVT S', 'Maruti Celerio Green VXI', 'Chevrolet Sail 1.2 Base', 'Tata Indigo Grand Petrol', 'Toyota Corolla Altis 1.8 VL CVT'],
    'ano': [2007, 2007, 2012, 2017, 2014, 2007, 2016, 2014, 2015, 2017, 2015, 2014, 2018],
    'preço': [60000, 135000, 600000, 250000, 450000, 140000, 550000, 240000, 850000, 365000, 260000, 250000, 1650000],
    'combustivel': ['Petrol', 'Petrol', 'Diesel', 'Petrol', 'Diesel', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'CNG', 'Petrol', 'Petrol', 'Petrol']
}

data = pd.DataFrame(carros)

print(data)

                             modelo   ano    preço combustivel
0                     Maruti 800 AC  2007    60000      Petrol
1          Maruti Wagon R LXI Minor  2007   135000      Petrol
2              Hyundai Verna 1.6 SX  2012   600000      Diesel
3            Datsun RediGO T Option  2017   250000      Petrol
4             Honda Amaze VX i-DTEC  2014   450000      Diesel
5              Maruti Alto LX BSIII  2007   140000      Petrol
6         Hyundai Xcent 1.2 Kappa S  2016   550000      Petrol
7          Tata Indigo Grand Petrol  2014   240000      Petrol
8          Hyundai Creta 1.6 VTVT S  2015   850000      Petrol
9          Maruti Celerio Green VXI  2017   365000         CNG
10          Chevrolet Sail 1.2 Base  2015   260000      Petrol
11         Tata Indigo Grand Petrol  2014   250000      Petrol
12  Toyota Corolla Altis 1.8 VL CVT  2018  1650000      Petrol

4. Mostre o nome e o preço para o carro na linha 5 formatado em real.
5. Mostre o nome, o ano e o tipo de combustível para o carro na linha 10 formatado em real, no seguinte formato:

    `Chevrolet Sail 1.2 Base ( 2015 ) : Petrol`

In [3]:
print(data.iloc[5][0], f'R${data.iloc[5][2]}')
print(data.iloc[10][0], "(", data.iloc[10][1], ") :", data.iloc[10][3])

Maruti Alto LX BSIII R$140000
Chevrolet Sail 1.2 Base ( 2015 ) : Petrol

## Exercício 2

1. Você recebeu uma base de uma planilhas e precisa fazer um **relatório** para seu chefe com alguns **dados sobre a base de clientes**. Isso é importante para pois ele vai adicionar essa informação a uma apresentação para os investidores. Ele precisa:

- Quantidade de clientes
- Quantidade de informações que é coletada por cliente
- O tamanho total da base

> *Você pode assumir que essa base foi tratada e não existem clientes repetidos.*

*Você deve utilizar o **código a seguir** para a base de clientes, caso não esteja na área de código do exercício, copie e cole.*

```python
# BASE DE CLIENTES
base = pd.read_csv("https://storage.googleapis.com/pedagogico/formacao-dados/tabela_clientes.csv")
```

In [7]:
# BASE DE CLIENTES
base = pd.read_csv("https://storage.googleapis.com/pedagogico/formacao-dados/tabela_clientes.csv")

#Resolução:
print("Quantidade de clientes:", len(base))
print("quantidade de informações por cliente:", base.shape[1])
print("Tamanho total da base:", base.size)

Quantidade de clientes: 500
quantidade de informações por cliente: 5
Tamanho total da base: 2500

## Exercício 3

Você está trabalhando em um centro de **pesquisa** sobre **vida marinha** e o professor pesquisador achou essa base sobre pinguins que seria muito interessante de ser incorporada ao trabalho. **Ele pediu para que você explore essa base e decida se é ela é consistente o suficiente para ser utilizada.**

1. Importe o `seaborn` e carregue a base `penguins` em uma variável.
2. Mostre um resumo dos tipos de variáveis
3. Mostre os primeiros 5 items da base
4. Mostre os últimos 5 items da base

Legenda/Contexto:
- Species: Espécie
- Island: Ilha
- Bill: Bico - [(Imagem de Referência)](https://allisonhorst.github.io/palmerpenguins/reference/figures/culmen_depth.png)
- Flipper: Nadadeira
- Body Mass: Massa corporal
- Sex: Sexo

In [9]:
import seaborn as sns

ping = sns.load_dataset('penguins')

print(ping.dtypes, "\n\n")

print("Primeiros: \n", ping.head(), "\n\n", ping.tail())

species               object
island                object
bill_length_mm       float64
bill_depth_mm        float64
flipper_length_mm    float64
body_mass_g          float64
sex                   object
dtype: object


Primeiros:
   species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0
1  Adelie  Torgersen            39.5           17.4              186.0
2  Adelie  Torgersen            40.3           18.0              195.0
3  Adelie  Torgersen             NaN            NaN                NaN
4  Adelie  Torgersen            36.7           19.3              193.0

   body_mass_g     sex
0       3750.0    Male
1       3800.0  Female
2       3250.0  Female
3          NaN     NaN
4       3450.0  Female

     species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
339  Gentoo  Biscoe             NaN            NaN                NaN
340  Gentoo  Biscoe            46.8           14.3              215.0
341  Gentoo  Biscoe            50.4           15.7              222.0
342  Gentoo  Biscoe            45.2           14.8              212.0
343  Gentoo  Biscoe            49.9           16.1              213.0

     body_mass_g     sex
339          NaN     NaN
340       4850.0  Female
341       5750.0    Male
342       5200.0  Female
343       5400.0    Male

Depois que você recebeu essa base, precisa passar um **relatório** para o professor pesquisador, para juntos decidirem se essa base pode ser considera ao estudo. Informações a serem passadas:

5. Quantidade de observações não-nulas por coluna
6. Valores mínimos e máximos de cada coluna
7. A média e a mediana dos valores

In [10]:
print('Valores válidos: \n', ping.count(), '\n\n')
print('Valores mínimos: \n', ping.min(), '\n\n')
print('Valores máximos: \n', ping.max(), '\n\n')
print('Média valores: \n', ping.mean(), '\n\n')
print('Mediana valores: \n', ping.median())

Valores válidos:
 species              344
island               344
bill_length_mm       342
bill_depth_mm        342
flipper_length_mm    342
body_mass_g          342
sex                  333
dtype: int64


Valores mínimos:
 species              Adelie
island               Biscoe
bill_length_mm         32.1
bill_depth_mm          13.1
flipper_length_mm     172.0
body_mass_g          2700.0
dtype: object


Valores máximos:
 species                 Gentoo
island               Torgersen
bill_length_mm            59.6
bill_depth_mm             21.5
flipper_length_mm        231.0
body_mass_g             6300.0
dtype: object


Média valores:
 bill_length_mm         43.921930
bill_depth_mm          17.151170
flipper_length_mm     200.915205
body_mass_g          4201.754386
dtype: float64


Mediana valores:
 bill_length_mm         44.45
bill_depth_mm          17.30
flipper_length_mm     197.00
body_mass_g          4050.00
dtype: float64

<ipython-input-10-40b9001c8d3e>:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print('Valores mínimos: \n', ping.min(), '\n\n')
<ipython-input-10-40b9001c8d3e>:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print('Valores máximos: \n', ping.max(), '\n\n')
<ipython-input-10-40b9001c8d3e>:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print('Média valores: \n', ping.mean(), '\n\n')
<ipython-input-10-40b9001c8d3e>:5: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print('Mediana valores: \n', ping.median())

## Exercício 4

O seu chefe do **exercício 2**. Esqueceu de te pedir outras informações muito importantes sobre a base de clientes e você deve enviar para ele agora:
1. Quais são as informações coletadas sobre os clientes
2. A lista de nomes e telefones para que o marketing entre em contato com os clientes para uma ação.
3. É importante ordenar os nomes por ordem alfabética
4. Bônus: Exporte essa nova tabela para um CSV e faça download dele

In [13]:
# BASE DE CLIENTES
base = pd.read_csv("https://storage.googleapis.com/pedagogico/formacao-dados/tabela_clientes.csv")

#resolução:
#1
print("Dados coletados dos clientes: ", ", ".join(base.columns))
#2, 3
base_telefones = base[['nome', 'telefone']]
base_telefones = base_telefones.sort_values('nome')
print(base_telefones)

#4(bônus)
from google.colab import files
base_telefones.to_csv('clientes_telefones.csv')
files.download('clientes_telefones.csv')

Dados coletados dos clientes:  nome, telefone, email, cep, estado
                nome        telefone
86        Aaron Byrd  1-123-343-7816
4        Abbot Knapp  1-475-850-6484
226   Abdul Petersen  (745) 597-2584
393      Abel Garner  (624) 917-6370
23   Abigail Solomon  1-565-818-9313
..               ...             ...
321     Zeph Preston  (880) 532-3480
313       Zeph Sykes  1-328-275-8090
72      Zephania Cox  1-228-876-3948
170    Zephania Ruiz  1-576-831-2548
490   Zorita Baldwin  (359) 129-7668

[500 rows x 2 columns]

## Exercício 5

Para esse exercício a gente precisa simular valores para uma base de vendas. O time de negócios precisa entender o quanto seria o impacto nas vendas se eles fizessem alterações nos valores dos produtos. Você precisa passar alguns cenários para eles.

1. Antes de fazer as contas, é necessário criar uma coluna com o valor total da compra, isso significa multiplicar a quantidade de produtos pelos seus valores.

**Cenários requisitados:**

1. Se aumentarmos os valores de todos os produtos em 5%
2. Qual a média de preço após essa operação
3. Se diminuirmos os valores de todos os produtos em 10%
4. Qual a mediana de preço após essa operação


*Você deve utilizar o **código a seguir** para a base de clientes, caso não esteja na área de código do exercício, copie e cole.*


```python
# BASE DE VENDAS
base = pd.read_json("https://storage.googleapis.com/pedagogico/formacao-dados/tabela_vendas.json")
```

In [25]:
# BASE DE VENDAS
base = pd.read_json("https://storage.googleapis.com/pedagogico/formacao-dados/tabela_vendas.json")

#Criando uma coluna com o total
base['total'] = base['quantidade'].mul(base['valor_produto'])

#Simulando cenários
##Aumento de 5%
base['total_mais_5p'] = base['total'].mul(1.05)
##Redução de 10%
base['total_menos_10p'] = base['total'].mul(0.9)

print(base[['total_mais_5p']].mean())
print(base[['total_menos_10p']].median())

total_mais_5p    264.222357
dtype: float64
total_menos_10p    169.137
dtype: float64