#Exercícios

##Exercício 1

Nos exercícios de Listas você fez a seguinte questão:

> Faça um programa que conta quantas letras *“a”* existem numa determinada palavra. Imprima o resultado na tela.

**Vamos repetir esse mesmo exercício elevando a complexidade juntando conceitos** que você já aprendeu até agora. Para resolver você deve utilizar os **seguintes requisitos:**
- O código precisa ser **envolvido em uma função `conta_letras`** para que possa ser reutilizado
- A função `conta_letras` precisa ter **2 argumentos**:
    1. O caractere que será contado
    2. A String que precisamos verificar
- Usar a técnica de **List Comprehension** para percorrer a String

In [7]:
def conta_letras(letra, texto):
  lista = [1 if item == letra else 0 for item in texto]
  return(sum(lista))

conta_letras("x", "alo")

0

##Exercício 2
Para a base de vendas, crie uma função lambda que aplica um desconto de 10% para compras acima de 5 produtos.

Para acessar a base, utilize o seguinte código:



```
# BASE DE VENDAS
base = pd.read_json("https://storage.googleapis.com/pedagogico/formacao-dados/tabela_vendas.json")
```

In [10]:
# BASE DE VENDAS
base = pd.read_json("https://storage.googleapis.com/pedagogico/formacao-dados/tabela_vendas.json")

base['valor_produto_novo'] = base[['quantidade', 'valor_produto']].apply(lambda x: x['valor_produto']*0.9 if x['quantidade'] > 5 else x['valor_produto'], axis = 1)

base

,id_compra,codigo_produto,region,quantidade,valor_produto,valor_produto_novo
0,EJF38SUC4TS,1002,Paraná,1,3.81,3.810
1,YDQ17YLX1MY,1264,São Paulo,8,77.51,69.759
2,DNK32LCC1RB,2344,Maranhão,3,16.92,16.920
3,DHJ68CCE3OP,9273,Maranhão,1,66.14,66.140
4,RQD46YMW6JT,1264,Santa Catarina,3,38.45,38.450
...,...,...,...,...,...,...
495,KPM96WTU5LI,8974,Maranhão,4,7.41,7.410
496,ZIT25VJB8GX,823,Rio Grande do Sul,0,14.62,14.620
497,FKL37EMH1AS,1002,Rio de Janeiro,9,46.22,41.598
498,SNY86RFP1YM,1002,Rio de Janeiro,10,10.75,9.675
499,OZC87SGF9WE,1002,Maranhão,6,94.89,85.401

##Exercício 3
Para que o aluno seja aprovado é necessário ter uma média  acima de 7.

Escreva um código que receba uma lista de dicionários contendo as notas, faça o cálculo e retorne o nome do aluno, a média e se ele foi aprovado no seguinte padrão:


```
aprovacoes = [
	{
		nome: "Warren Trindade",
		media: 8.8,
		aprovado: True,
	},
    {
		nome: "Steven Aguiar",
		media: 4.8,
		aprovado: False,
	},
    ...
]
```

Após isso, exiba na tela todos os alunos no seguinte padrão:

```
Warren Trindade -> Aprovado(a) - 8.8;
Steven Aguiar -> Reprovado(a) - 4.8;
---
Indicadores da turma:
Aprovados 1/2 => 50%
Reprovados 1/2 => 50%
```

In [17]:
# Base a ser utilizada
alunos = [
	{
		'nome': "Warren Trindade",
		'notas': [7, 1, 9, 8, 10, 2, 3],
		'email': "nunc.ac@yahoo.ca"
	},
	{
		'nome': "Selma Messias",
		'notas': [7, 2, 1, 9, 6],
		'email': "rutrum.magna.cras@protonmail.ca"
	},
	{
		'nome': "Steven Aguiar",
		'notas': [5, 8, 2, 7, 4, 9],
		'email': "quisque@aol.net"
	},
	{
		'nome': "Kyle Rezende",
		'notas': [8, 3, 4, 7, 5],
		'email': "vel@protonmail.ca"
	},
	{
		'nome': "Aimee Barboza",
		'notas': [1, 9, 8, 5, 10, 3, 2],
		'email': "pharetra.ut@outlook.com"
	},
	{
		'nome': "Tanya Cavalcante",
		'notas': [8, 10, 5, 4, 3, 9, 6],
		'email': "suscipit.nonummy@outlook.couk"
	},
	{
		'nome': "Kai Miranda",
		'notas': [6, 7, 5, 2, 10, 4, 8],
		'email': "pede.sagittis@yahoo.com"
	},
	{
		'nome': "Lael dos Reis",
		'notas': [9, 6, 3, 4, 1, 10],
		'email': "ipsum.non@protonmail.ca"
	},
	{
		'nome': "Adrienne Pires",
		'notas': [5, 10, 6, 8, 4],
		'email': "metus.eu.erat@aol.com"
	},
	{
		'nome': "Wynne Marinho",
		'notas': [5, 4, 2, 3, 7],
		'email': "euismod.in.dolor@yahoo.ca"
	}
]

from functools import reduce

for item in alunos:
	item['media'] = reduce(lambda a,b: a+b, item['notas']) / len(item['notas'])
	if item['media'] >= 6:
		item['aprovado'] = True
	else:
		item['aprovado'] = False

	item.pop('notas')
	item.pop('email')

alunos

[{'nome': 'Warren Trindade', 'media': 5.714285714285714, 'aprovado': False},
 {'nome': 'Selma Messias', 'media': 5.0, 'aprovado': False},
 {'nome': 'Steven Aguiar', 'media': 5.833333333333333, 'aprovado': False},
 {'nome': 'Kyle Rezende', 'media': 5.4, 'aprovado': False},
 {'nome': 'Aimee Barboza', 'media': 5.428571428571429, 'aprovado': False},
 {'nome': 'Tanya Cavalcante', 'media': 6.428571428571429, 'aprovado': True},
 {'nome': 'Kai Miranda', 'media': 6.0, 'aprovado': True},
 {'nome': 'Lael dos Reis', 'media': 5.5, 'aprovado': False},
 {'nome': 'Adrienne Pires', 'media': 6.6, 'aprovado': True},
 {'nome': 'Wynne Marinho', 'media': 4.2, 'aprovado': False}]

In [21]:
contagem_aprovados = 0
for item in alunos:
  if item['aprovado']:
    status = "Aprovado(a)"
    contagem_aprovados += 1
  else:
    status = "Reprovado(a)"
  print(item['nome'], "->", status, " - ", item['media'])

print("---")
print("indicadores da Turma:")
print("Aprovados:", (contagem_aprovados / len(alunos)*100), "%")
print("Reprovados:", ((len(alunos) - contagem_aprovados)/ len(alunos))*100, "%")

Warren Trindade -> Reprovado(a)  -  5.714285714285714
Selma Messias -> Reprovado(a)  -  5.0
Steven Aguiar -> Reprovado(a)  -  5.833333333333333
Kyle Rezende -> Reprovado(a)  -  5.4
Aimee Barboza -> Reprovado(a)  -  5.428571428571429
Tanya Cavalcante -> Aprovado(a)  -  6.428571428571429
Kai Miranda -> Aprovado(a)  -  6.0
Lael dos Reis -> Reprovado(a)  -  5.5
Adrienne Pires -> Aprovado(a)  -  6.6
Wynne Marinho -> Reprovado(a)  -  4.2
---
indicadores da Turma:
Aprovados: 30.0 %
Reprovados: 70.0 %

##Exercício 4
A empresa na qual você trabalha deseja abrir um **serviço de entrega nos estados da Região Nordeste** e para validar o negócio é necessário **responder algumas perguntas dos investidores:**

1. A quantidade de clientes que seriam beneficiados deste novo produto.
2. A quantidade de clientes em potencial nas outras regiões do país.

Depois de uma pesquisa rápida no google você achou [esse artigo sobre como identificar os números dos CEPs](https://mundoeducacao.uol.com.br/curiosidades/o-que-significam-os-numeros-cep.htm) e retirou a seguinte informação:

>Cada algarismo do CEP possui um significado. **Da esquerda para a direita, os números indicam a região** [...] O Brasil é dividido em dez regiões postais, que compõem o primeiro dos números do CEP:
>
>Região 0 - Grande São Paulo;
>
>Região 1 - Interior de São Paulo;
>
>Região 2 - Rio de Janeiro e Espírito Santo;
>
>Região 3 - Minas Gerais;
>
>Região 4 - Bahia e Sergipe;
>
>Região 5 - Pernambuco, Alagoas, Paraíba e Rio Grande do Norte;
>
>Região 6 - Ceará, Piauí, Maranhão, Pará, Amazonas, Acre, 
Amapá e Roraima;
>
>Região 7 - Distrito Federal, Goiás, Tocantins, Mato Grosso, Mato Grosso do Sul e Rondônia;
>
>Região 8 - Paraná e Santa Catarina;
>
>Região 9 - Rio Grande do Sul.


**Para acessar a base utilize o seguinte código:**

```
# BASE DE CLIENTES
base = pd.read_csv("https://storage.googleapis.com/pedagogico/formacao-dados/tabela_clientes.csv")

```

In [26]:
# BASE DE CLIENTES
base = pd.read_csv("https://storage.googleapis.com/pedagogico/formacao-dados/tabela_clientes.csv")

base['cep_1dig'] = base['cep'].apply(lambda x: str(x)[0])

def de_para_regiao(regiao_cep, estado):
  regiao_cep = int(regiao_cep)

  if regiao_cep in [0,1,2,3]:
    return("Sudeste")
  elif regiao_cep in [8,9]:
    return("Sul")
  elif regiao_cep in [4,5,6] and estado not in ['Pará', 'Amazonas', 'Acre', 'Amapá' , 'Roraima']:
    return("Nordeste")
  elif estado in ['Pará', 'Amazonas', 'Acre', 'Amapá' , 'Roraima', 'Tocantins', 'Rondônia']:
    return('Norte')
  elif regiao_cep == 7 and estado not in ['Tocantins', 'Rondônia']:
    return("Centro-Oeste")

base['regiao'] = base.apply(lambda x: de_para_regiao(x['cep_1dig'], x['estado']), axis = 1)

base['regiao'].value_counts()

Nordeste        207
Sul             127
Sudeste         107
Centro-Oeste     41
Norte            18
Name: regiao, dtype: int64